#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const langsDir = join(root, 'langs');
const codes = [
  'en', 'ru', 'es', 'de', 'fr', 'uk', 'zh', 'hi', 'ar', 'pt', 'ja', 'ko', 'it', 'tr',
];

const entries = codes.map((code) => {
  const html = readFileSync(join(langsDir, `${code}.html`), 'utf8').trim();
  return `  ${code}: ${JSON.stringify(html)}`;
});

const out = `/* Generated by npm run build — do not edit by hand */
window.PRIVACY_CONTENT = {
${entries.join(',\n')}
};
`;

writeFileSync(join(root, 'content.js'), out);
console.log('Built content.js (' + codes.length + ' languages)');
